name: Build MacOS

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      binary:
        required: true
        type: string
      run_macos_intel:
        required: true
        type: string
      run_macos_apple_silicon:
        required: true
        type: string


jobs:
  build-macos-intel:
    if: inputs.run_macos_intel == 'true'
    name: macos_intel
    env:
      platform: macos_intel
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Environment Setup
        run: |
          export CFLAGS="-fno-stack-check"
          export MACOSX_DEPLOYMENT_TARGET="10.9"

      - name: Build
        run: |
          cargo build --release --target x86_64-apple-darwin

      - name: Set Paths
        id: set_paths
        run: |
          echo "file_name=${{ inputs.binary }}_${{ inputs.tag }}_${{ env.platform }}" >> "$GITHUB_OUTPUT"
          echo "app_structure=${{ inputs.binary }}.app/Contents/MacOS" >> "$GITHUB_OUTPUT"

      - name: Prepare Package
        run: |
          mkdir -p ${{ steps.set_paths.outputs.app_structure }}
          cp target/x86_64-apple-darwin/release/${{ inputs.binary }} ${{ steps.set_paths.outputs.app_structure }}
          cp -r assets ${{ steps.set_paths.outputs.app_structure }}
          hdiutil create -fs HFS+ -volname "${{ inputs.binary }}" -srcfolder ${{ inputs.binary }}.app ${{ steps.set_paths.outputs.file_name  }}.dmg

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.platform }}
          path: ${{ steps.set_paths.outputs.file_name  }}.dmg
          retention-days: 1
        
  build-macos-apple-silicon:
    name: macos_apple_silicon
    if: inputs.run_macos_apple_silicon == 'true'
    env:
      platform: macos_apple_silicon
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Environment
        # macos 11 was the first version to support ARM
        run: |
          export MACOSX_DEPLOYMENT_TARGET="11"

      - name: Build
        run: |
          cargo build --release --target aarch64-apple-darwin

      - name: Set paths
        id: set_paths
        run: |
          echo "file_name=${{ inputs.binary }}_${{ inputs.tag }}_${{ env.platform }}" >> "$GITHUB_OUTPUT"
          echo "app_structure=${{ inputs.binary }}.app/Contents/MacOS" >> "$GITHUB_OUTPUT"

      - name: Prepare Package
        run: |
          mkdir -p ${{ steps.set_paths.outputs.app_structure }}
          cp target/aarch64-apple-darwin/release/${{ inputs.binary }} ${{ steps.set_paths.outputs.app_structure }}
          cp -r assets ${{ steps.set_paths.outputs.app_structure }}
          hdiutil create -fs HFS+ -volname "${{ inputs.binary }}" -srcfolder ${{ inputs.binary }}.app ${{ steps.set_paths.outputs.file_name  }}.dmg

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.platform }}
          path: ${{ steps.set_paths.outputs.file_name  }}.dmg
          retention-days: 1